### ISSUE TITLE
system:update gives entity table keyed by the entries, forcing use of (slow!) pairs()

### ISSUE THREAD

**Issue by shakesoda** [bakpakin/tiny-ecs#1]
The inverted table given to system update is really weird and I couldn't see any rationale for it.

[pairs() can't be compiled by LuaJIT](http://wiki.luajit.org/NYI#Base-Library), so whenever you call it you incur a performance penalty by throwing things back to interpreter mode - I'm not normally too stingy about this (no big deal in low-frequency stuff), but for something that will happen as often as entity updates for the various systems a game has it's a bit of a red flag.

Can the table be inverted such that it will work with ipairs? What's with the values (true, true, true...)?

**Comment by bakpakin** [comment]
I was justing fixing this. This is something I wrote in early to keep the code clean. I just pushed another branch(dev) that reimplemented this in a more traditional fashion. Also, the inversion made adding and removing Entities faster, although you're right that iterating Entities should be the first thing optimized.

**Comment by bakpakin** [comment]
Just deleted the dev branch, and moved the changes to master.

**Comment by shakesoda** [comment]
Awesome, thanks! Other than the docs being pretty sparse (as you've noted in your todo already), that's the only thing I've run into so far which has been a concern.
