### ISSUE TITLE
Tiny-ecs somehow interfering with Love2D rendering.

### ISSUE THREAD

**Issue by falsechicken** [bakpakin/tiny-ecs#12]
Hey! Sorry for blowing up the issues page like this. This is likely something that is my fault but I honestly cannot figure it out. After you solved my problem in issue 11 I ran into another one. My render system is running but love.graphics.print is not working. When I do NOT pass the delta time into the update function (just the filter) the graphics call works. When I do pass the delta time in it doesn't. Even through the system is running as indicated by my print statements I threw in there to debug. Any suggestions? I re-opened the last issue because it contains relevant info.

[https://github.com/bakpakin/tiny-ecs/issues/11](https://github.com/bakpakin/tiny-ecs/issues/11)

Thank you for your time! I have been playing with this all night trying to figure it out.

**Comment by bakpakin** [comment]
You are probably calling love.graphics.print NOT inside love.draw. Make sure that whatever system is calling love.graphics.print is being updated inside love.draw. When you call world.update without a filter, you update every system, including the drawing systems that you might not want to update. I'm guessing you are updating a rendering system inside love.update. When the love.draw is called, I believe it will clear the canvas and any rendering that your systems may have done.

One way around this is to only call world.update in love.draw, and use love.timer.getDelta (I think it is called that) to get the delta time. All systems will behave normally, but your rendering code will happen interspersed with your logic code.

This isn't a problem with tiny-ecs, as tiny-ecs has literally no knowledge of LOVE.

**Comment by falsechicken** [comment]
Ok I will play with this now and get back. Thanks for taking the time to answer my mundane noob questions!
