### ISSUE TITLE
A few feature requests / questions

### ISSUE THREAD

**Issue by Substr** [bakpakin/tiny-ecs#13]
Hi, thanks for making such a great library! I've been seeing if it's a good fit for my game, and found a few features I think would be useful to have. It may be that there's already ways to do some of these  that I've missed, but I'd be interested in hearing your comments.

### Systems that handle multiple entity collections

I have a few cases where a system needs to work on two distinct sets of entities. It would be great if something like this were possible:
```
testsystem.filter = {
    items = tiny.requireAll("ComponentA"),
    otherItems = tiny.requireAll("ComponentB")
}
```

and then inside the system, you'd have `system.entities.items` and `system.entities.otherItems` available. Of course this would really only work and make sense when using a regular `tiny.system()` and not a `processingSystem()`, so then it's up to the developer to implement their own `update()` method and iterate over entities etc.

### Being able to easily fetch collections of entities

Maybe related to the thing above, but having an easy way to do something like this would be really useful:
```
someEnts = world.getEntities(tiny.requireAll("SomeComponent"))
```

I notice there's the world.entities collection, and you already have the tiny.filter() method, so this could probably be achieved already simply by looping over them and filtering, but I'm not sure how well this would perform with large entity collections -- but this feature would be more useful for things like debugging anyway probably. If you needed multiple collections inside of a system, then maintaining the separate lists like above would be better.

Thanks!

**Comment by bakpakin** [comment]
To have a single system process two sets of entities, my suggestion would be to create two systems, and give a reference of one system to the other. This is not as clean as it could be, but it should be simple and fast.

For fetching collections on entities, you could just iterate all entities in the world and filter them. That would be slow, but if it is only for debugging, that's fine. If you want to do this in game, just add another system with no update function. The entities you need will be in system.entities.

**Comment by shakesoda** [comment]
for multiple entity sets I just make a system which matches everything I need (tiny.requireAny(tiny.requireAll(set1), tiny.requireAll(set2)) and maintain the lists in onAdd/onRemove. Gluing systems together also works, as mentioned.

**Comment by Substr** [comment]
Thanks both, that points me in the right direction.
