### ISSUE TITLE
Entity’s properties caching

### ISSUE THREAD

**Issue by neoascetic** [bakpakin/tiny-ecs#17]
```lua
> t = require 'tiny'
> e = {name='Ivan'}
> s = t.processingSystem()
> function s:process(e) print(e.name) end
> s.filter = t.requireAll('name')
> w = t.world(e, s)
> w:update()
Ivan
> e.name = nil
> w:update()
nil
```

Is that expected behaviour? As a workaround I am currently re-adding changed entity to the world, but maybe there is a better (i. e. automatic) way?

Thank you.

**Comment by shakesoda** [comment]
the filter is only checked on add. this is expected.

**Comment by bakpakin** [comment]
Shakesoda is correct. I will close this issue.

**Comment by neoascetic** [comment]
Okay, so my workaround is the correct way to do things? 

This is a little bit inconvenient thought because one of the features of ECS is the ability to change the list of components dynamically at runtime. Maybe there should be a special method to "notify" world about changes (with the corresponding name).

Thank you.

**Comment by bakpakin** [comment]
Yes that special method is the add function. There should be no need to remove the entity first.

**Comment by coderofsalvation** [comment]
@neoascetic necrobumping this fwiw (and note to self)

the filter selects entities when the system is [added to the world](https://github.com/bakpakin/tiny-ecs/blob/master/tiny.lua#L593)..a snapshot of that moment so to speak:

```lua
s.filter = t.requireAll('name')   -- this builds a cache of entities (=fast performace)
```

a bit hidden in the docs, but executing the filter on every call can be done like so:

```lua
s.nocache = true -- dont use the entities cache (**expensive**)
```

a more efficient way would be rebuilding the cache when `commit()` is expliclity called (instead of filtering **every** update via `s.nocache = true`)

```lua

-- recalculate filters for tiny-ecs systems
commitify = function(world) 
  return function()
    for j = 1, #world.entities do
      local system = world.systems[j]
      system.entities = {}
      for j = 1, #world.entities do
        local entity = world.entities[j]
        if system.filter(system, entity) then
          table.insert( system.entities, entity)
        end
      end
    end
  end
end

 -- do this once
w.commit = commitify(w)

-- now you can do this:
e.name = "changed!"
w.commit() -- this will rebuild the cache of the systems (without disabling onAdd/onRemove/etc like `nocache = true` does)

```

This function could
